version: "3.8"
services:
  web:
   image: nginx:latest
   ports:
     - "8080:80"
   volumes:
     - ./src:/usr/share/nginx/html
     - ./web.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:7-fpm
    volumes:
      - ./src:/usr/share/nginx/html
